name: SpeakNote iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-Lobanov/setup-xcode@v1
      with:
        Xcode-version: '14.2.0'

    - name: Build SpeakNote project
      run: xcodebuild -project SpeakNote.xcodeproj -scheme SpeakNote -sdk iphonesimulator -configuration Debug

    - name: Run tests
      run: xcodebuild test -project SpeakNote.xcodeproj -scheme SpeakNote -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'
